version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12

    working_directory: /root/repo

    steps:
      - attach_workspace:
          at: /root/repo

      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn build

      - persist_to_workspace:
          root: /root/repo
          paths:
            - null
  
  deploy:
    docker:
      - image: circleci/node:12
    
    steps:
      - attach_workspace:
          at: /root/repo
          
      - run:
          name: 'Deploy to Firebase Hosting'
          command: './node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN'

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build