on: push
name: Build and deploy on push
jobs:
  install:
    name: Install
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install
      uses: nuxt/actions-yarn@master
      with:
        args: install
    - name: Build
      uses: nuxt/actions-yarn@master
      with:
        args: build
    - name: Deploy to Firebase
      uses: w9jds/firebase-action@master
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      with:
        args: deploy --only hosting
